
services:
  resume-magic:
    build: .
    ports:
      - "1771:1771"
    environment:
      - BROWSERLESS_API_KEY=${BROWSERLESS_API_KEY}
      - BROWSERLESS_URL=${BROWSERLESS_URL}
      - BASE_URL=${BASE_URL}
    volumes:
      - .:/app
     
    restart: unless-stopped
